### PR TITLE
Make the pagination url honour any other GET params

### PR DESCRIPTION
**Pull request by alexbrindalsl**

### CODE REVIEW

**Comment by takobell** [comment]
What's the use-case for this?

**Comment by alexbrindalsl** [comment]
We are passing variable on the GET params such as "limit=5" (such as a summary content area) etc which influence the criteria for number returned per page - using the provided next page url as it currently stands strips any GET additional params - so in this case, the first page would show 5, the second page would show 10, and there's 5 entries between which are lost.

**Comment by carlcs** [comment]
Oh, there's already a PR for this, if I'd only noticed this 5 mins ago... Thanks!
@takobell: here's a use case https://github.com/pixelandtonic/ElementAPI/issues/9

**Comment by zizther** [comment]
I have tried and tested this. It is a useful feature. +1

**Comment by takobell** [comment]
Resolved in https://github.com/pixelandtonic/ElementAPI/releases/tag/1.2.1

**Pull request closed without merging**
