### PR TITLE
Moved everything out of the elementapi folder for composer usage.

### PR DESCRIPTION
**Pull request by roelvanhintum**
`composer/installer` doesn't work when the plugin itself is nested in the `elementapi` folder.

### CODE REVIEW

**Comment by timkelty** [comment]
😊

**Comment by roelvanhintum** [comment]
Can I get any feedback on what is wrong with this pull-request?

**Comment by timkelty** [comment]
@roelvanhintum I'm trying to get some guidance from composer contributors here: https://github.com/composer/installers/issues/286#issuecomment-258144004

**Comment by takobell** [comment]
We've got composer/plugin plans for the upcoming Craft 3 release we're planning on making across the whole Craft 3 plugin ecosystem that would make this moot.

**Pull request closed without merging**
