### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by jackmcpickle**

### CODE REVIEW

**Comment by jackmcpickle** [comment]
preferably the folder structure would change to have the contents at the root level - but will leave that up to you.

**Comment by takobell** [comment]
Thanks!

**Comment by carlcs** [comment]
How do you mean "preferably", @jackmcpickle? Your changes to the composer.json only really make a difference after the files from elementapi/ are moved to the root of the repo. Still can't install using composer with how it's setup currently, can you?

**Comment by timkelty** [comment]
You can use a Composer `post-install-cmd` script to move things into place, which is certainly _not_ preferable, but works.

**Comment by timkelty** [comment]
Hopefully this gets merged in: https://github.com/nystudio107/generator-craftplugin/pull/5 and people us that scaffolding more to avoid these kind of PRs.

**Comment by carlcs** [comment]
If only composer / composer-installers would have support for sparse checkout...
http://stackoverflow.com/a/19304727/3699394

**Comment by jackmcpickle** [comment]
This is what we are doing for plugins that don't have root file approach. 

```
"scripts": {
    "post-install-cmd": [
        "/bin/bash -c 'pushd craft/plugins && test -d elementapi/elementapi && mv elementapi/elementapi/* elementapi && popd'",
    ]
}
```
The other part that is missing is a git tag relating to the right version

**Pull request merged**
